import type { Metadata } from "next";
import { Fira_Code } from 'next/font/google'
import "./globals.css";

const fira_code = Fira_Code ({ 
  subsets: ['latin'], 
  weight: ['300', '400', '500']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={fira_code.className}>
      {children}
    </body>
  </html>
  );
}
